image: ruby:2.3

skripsi:
  stage: skripsi
  script:
  - gem install jekyll
  - jekyll build -d skripsi
  artifacts:
    paths:
    - skripsi
  except:
  - master

pages:
  stage: deploy
  script:
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
